Feat/events crud p2 6
ieee-odc/event-toolbox pull request #8
Opened 2024-07-08 11:05 UTC by oveed

2024-07-08 11:32 UTC, slimskhab requested changes
1 change than LGTM

2024-07-08 11:32 UTC, slimskhab commented on frontend/src/modules/Events/components/EventsList.jsx
> +    }
```suggestion
    try {
      const response = await axiosRequest.get("/events");
      setEvents(response.data);
    } catch (error) {
      console.error("Error fetching events:", error);
    }finally{
    setLoading(false);
    }
```

2024-07-09 08:21 UTC, ALABM1 approved these changes
LGTM

2024-07-09 08:22 UTC, ALABM1 approved these changes
LGTM

2024-07-09 08:34 UTC, slimskhab requested changes
- When I click on the event name it takes me to http://localhost:5173/app-academy-course-details.html
- Change the 34 to something live event Id or remove it
![image](https://github.com/ieee-odc/event-toolbox/assets/12747343/81f12251-07d9-4186-a177-b09943f305e8)
- I can choose a before date that is after the end date
![image](https://github.com/ieee-odc/event-toolbox/assets/12747343/86f0698b-22a1-4907-93d0-0c97361954bb)

2024-07-09 09:24 UTC, slimskhab approved these changes
LGTM!

2024-07-09 09:24 UTC, merged